### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slimakiswinka**
The Saving Mods feature works on the latest (8.3.14) version.

### CODE REVIEW

**Comment by slimakiswinka** [comment]
Should be noted that it didnt work but now works again.

**Comment by bennett-sh** [comment]
Are you really sure? For me it allows me to enable it but it won't actually save the mods.

**Comment by slimakiswinka** [comment]
I did make a quick test and yes it does but you have to turn them in the app settings and game settings, but im 99% sure thats how it is in wemod.

**Comment by slimakiswinka** [comment]
image
Those two have to be on

**Comment by slimakiswinka** [comment]
WeMod
Those two have to be on.
Mods save for me (tho i enabled them from the overlay but i dont think it matters)

**Pull request merged**
