### PR TITLE
Fix the dir for newer nodejs

### PR DESCRIPTION
**Pull request by slimakiswinka**
instead of Program Files/nodejs/ to Program Files/nodejs/node_modules/.bin/

### CODE REVIEW

**Comment by slimakiswinka** [comment]
also noticed that if you have new node it wont be in the root dir of node but in node_modules/.bin/

**Comment by bennett-sh** [comment]
Thanks for the contribution!
However, this path doesn't exist on my machine. I just noticed that the package can be installed into various locations (even %appdata%), which is why I won't use a specific path but instead I'll require asar to be in path. This should automatically be the case in most scenarious.

**Comment by slimakiswinka** [comment]
That is the default now so thats why the pull request exists.

**Comment by bennett-sh** [comment]
As I mentioned, I wasn't able to reproduce said path on my machine. That's why with v0.5.0 (now available), ```asar.cmd``` is required to be in PATH or one of the following directories:
- Program Files\nodejs
- Program Files\nodejs\node_modules\.bin (the directory you have your file in)
- App Data\npm

I'll probably do some more research to try and include every possible non-custom Node path.

**Pull request closed without merging**
